// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgmfVJgcGXZfHEViw_3EMSCWJu787o8c8',
    appId: '1:1036754373740:web:f5389e6cd609603775dc49',
    messagingSenderId: '1036754373740',
    projectId: 'india-story-project-27b9c',
    authDomain: 'india-story-project-27b9c.firebaseapp.com',
    databaseURL: 'https://india-story-project-27b9c-default-rtdb.firebaseio.com',
    storageBucket: 'india-story-project-27b9c.firebasestorage.app',
    measurementId: 'G-YRM1PPZDYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzdHC1h94a7w7vF0Sqr2LKP11VRIovnMA',
    appId: '1:1036754373740:android:7d3a36f4f17c439875dc49',
    messagingSenderId: '1036754373740',
    projectId: 'india-story-project-27b9c',
    databaseURL: 'https://india-story-project-27b9c-default-rtdb.firebaseio.com',
    storageBucket: 'india-story-project-27b9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPT0LnPb7bKJ0OoggKh0RxtvdtHnu6N8o',
    appId: '1:1036754373740:ios:301a2d58ecfef95775dc49',
    messagingSenderId: '1036754373740',
    projectId: 'india-story-project-27b9c',
    databaseURL: 'https://india-story-project-27b9c-default-rtdb.firebaseio.com',
    storageBucket: 'india-story-project-27b9c.firebasestorage.app',
    iosClientId: '1036754373740-cmi3leml6j69rgtddffqlfa5pgcm7kf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPT0LnPb7bKJ0OoggKh0RxtvdtHnu6N8o',
    appId: '1:1036754373740:ios:301a2d58ecfef95775dc49',
    messagingSenderId: '1036754373740',
    projectId: 'india-story-project-27b9c',
    databaseURL: 'https://india-story-project-27b9c-default-rtdb.firebaseio.com',
    storageBucket: 'india-story-project-27b9c.firebasestorage.app',
    iosClientId: '1036754373740-cmi3leml6j69rgtddffqlfa5pgcm7kf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgmfVJgcGXZfHEViw_3EMSCWJu787o8c8',
    appId: '1:1036754373740:web:9ad763b62ced2e8a75dc49',
    messagingSenderId: '1036754373740',
    projectId: 'india-story-project-27b9c',
    authDomain: 'india-story-project-27b9c.firebaseapp.com',
    databaseURL: 'https://india-story-project-27b9c-default-rtdb.firebaseio.com',
    storageBucket: 'india-story-project-27b9c.firebasestorage.app',
    measurementId: 'G-D4E3NTZZ5J',
  );
}
